"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { propertyRecords } from "./propertiesData";

export default function SimplePropertiesLayout() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => propertyRecords.filter((property) => property.name.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="min-h-screen bg-[#fbfaf8] pb-20 pt-14 sm:pt-24"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><header className="flex flex-col gap-5 rounded-3xl border border-[#e8dfd8] bg-white p-6 shadow-sm sm:flex-row sm:items-end sm:justify-between sm:p-8"><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-picasso-brown">Residences</p><h1 className="mt-2 font-serif text-4xl text-neutral-900">Find a place that fits.</h1><p className="mt-3 max-w-xl text-base text-neutral-600">Compare the essentials, choose a property, and apply when you are ready.</p></div><label className="text-sm font-medium text-neutral-700">Search residences<input value={query} onChange={(event)=>setQuery(event.target.value)} aria-label="Search residences" placeholder="e.g. Legends Lodge" className="mt-2 block h-12 w-full rounded-xl border border-[#d9ccc3] bg-white px-4 outline-none focus:border-picasso-brown sm:w-64" /></label></header><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((property)=><article key={property.id} className="overflow-hidden rounded-2xl border border-[#e8dfd8] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative h-52"><Image src={property.mainImage} alt={`${property.name} exterior`} fill className="object-cover" sizes="(max-width: 640px) 100vw, 33vw" /></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-semibold text-neutral-900">{property.name}</h2>{property.nsfasVerified ? <span className="rounded-full bg-[#edf5ef] px-2 py-1 text-xs font-semibold text-[#287343]">NSFAS</span> : null}</div><p className="mt-2 text-sm leading-6 text-neutral-600">{property.description}</p><p className="mt-4 text-sm font-medium text-neutral-800">{property.distance}</p><p className="mt-1 text-sm text-neutral-600">From R{property.priceFrom.toLocaleString()} · {property.roomTypes.join(" or ")}</p><div className="mt-5 flex gap-3"><Link href={`/properties/${property.slug}`} className="rounded-full bg-picasso-brown px-4 py-2 text-sm font-semibold text-white">View property</Link><Link href={`/apply?property=${property.slug}`} className="rounded-full border border-picasso-brown/30 px-4 py-2 text-sm font-semibold text-picasso-brown">Apply</Link></div></div></article>)}</div>{filtered.length===0 ? <p className="mt-10 rounded-xl bg-white p-6 text-neutral-600">No residence matches that search. Try a different name.</p> : null}</div></div>;
}
